"""
Script to create the default Word template for transcription exports.
Run this script once to generate the default template.
"""

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from pathlib import Path


def create_default_template():
    """Create a default Word template with placeholders"""
    doc = Document()

    # Set up styles
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    # Title
    title = doc.add_heading('{{title}}', level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Metadata Section
    doc.add_heading('Metadata', level=1)

    metadata_table = doc.add_table(rows=5, cols=2)
    metadata_table.style = 'Light Grid Accent 1'

    metadata_fields = [
        ("Export Date", "{{date}}"),
        ("Duration", "{{duration}}"),
        ("Number of Speakers", "{{num_speakers}}"),
        ("Language", "{{language}}"),
        ("Total Segments", "{{total_segments}}")
    ]

    for i, (label, placeholder) in enumerate(metadata_fields):
        row = metadata_table.rows[i]
        row.cells[0].text = label
        row.cells[1].text = placeholder
        # Make label bold
        row.cells[0].paragraphs[0].runs[0].bold = True

    doc.add_paragraph()  # Spacing

    # Transcription Section
    doc.add_heading('Transcription', level=1)

    # Add instruction paragraph
    instruction_para = doc.add_paragraph()
    instruction_run = instruction_para.add_run(
        "The transcription segments will be inserted below this line."
    )
    instruction_run.italic = True
    instruction_run.font.color.rgb = RGBColor(150, 150, 150)

    # Add transcription marker
    marker_para = doc.add_paragraph('{{TRANSCRIPTION}}')
    marker_para.add_run().add_break()

    # Footer
    doc.add_paragraph()
    footer_para = doc.add_paragraph()
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer_para.add_run("Generated by Audio Scribe AI")
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(150, 150, 150)
    footer_run.italic = True

    # Save template
    template_dir = Path(__file__).parent / "word"
    template_dir.mkdir(exist_ok=True)

    template_path = template_dir / "default_template.docx"
    doc.save(str(template_path))

    print(f"✓ Default template created: {template_path}")
    return template_path


if __name__ == "__main__":
    create_default_template()
